//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.22 at 04:34:15 PM IST 
//

package in.gov.uidai.otpapiclient.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "OtpResult")
@XmlEnum
public enum OtpResult {

	@XmlEnumValue("y")
	Y("y"), @XmlEnumValue("n")
	N("n");
	private final String value;

	OtpResult(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static OtpResult fromValue(String v) {
		for (OtpResult c : OtpResult.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
